// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVdSXzrNq8G-4hRC-kuocqnbAaEbVLaBY',
    appId: '1:3515536203:web:51d767ae07e33337918ece',
    messagingSenderId: '3515536203',
    projectId: 'login-y-registro-flutter',
    authDomain: 'login-y-registro-flutter.firebaseapp.com',
    storageBucket: 'login-y-registro-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWaa2g34_1AP9vEW8ljmmOGhqkGJnI2o0',
    appId: '1:3515536203:android:b6cd10e39b292870918ece',
    messagingSenderId: '3515536203',
    projectId: 'login-y-registro-flutter',
    storageBucket: 'login-y-registro-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9993LI8_MJAKvekp6ujYSV-qRELIaAcI',
    appId: '1:3515536203:ios:bbf79010c2d936e2918ece',
    messagingSenderId: '3515536203',
    projectId: 'login-y-registro-flutter',
    storageBucket: 'login-y-registro-flutter.appspot.com',
    iosClientId: '3515536203-41ti6nhtd57g0fh5t7g0m4o2tak4jggo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9993LI8_MJAKvekp6ujYSV-qRELIaAcI',
    appId: '1:3515536203:ios:bbf79010c2d936e2918ece',
    messagingSenderId: '3515536203',
    projectId: 'login-y-registro-flutter',
    storageBucket: 'login-y-registro-flutter.appspot.com',
    iosClientId: '3515536203-41ti6nhtd57g0fh5t7g0m4o2tak4jggo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginRegister',
  );
}
